version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    command: gunicorn --bind 0.0.0.0:8000 mysite.wsgi:application
    volumes:
      - ./backend:/app
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-_secret-key_here
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://backend:8000
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5433:5432"

volumes:
  postgres_data: 